name: BuildRaindrops

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  PLUGIN_NAME: Raindrops

jobs:
  build:
    strategy:
      matrix:
        platform: [x64, ARM64]

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read version
        run: |
          [xml]$xml = Get-Content -Path Directory.Build.Props
          $version = "$($xml.Project.PropertyGroup.Version)".Trim()
          echo "VERSION=$version" >> $env:GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Setup msbuild.exe
        uses: microsoft/setup-msbuild@v2

      

      - name: Restore packages
        run: msbuild Raindrops.sln /t:Restore /p:Configuration=Release

      - name: Build Plugin
        run: msbuild Raindrops\Raindrops.csproj /p:Configuration=Release /p:Platform=${{matrix.platform}} /p:Version=${{env.VERSION}} /p:AppxPackageDir=AppxPackages\

      - name: Prepare artifact
        run: |
          New-Item -Type Directory build
          Get-ChildItem -Path . -Recurse -Include *.msix | Where-Object { $_.FullName -match "\AppxPackages" } | ForEach-Object {
            Copy-Item -Path $_.FullName -Destination build
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{env.VERSION}}-${{matrix.platform}}
          path: build

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: Build*/*
